-- Criar o conjunto de opções para Magistrados
INSERT INTO public.option_sets (key, label, description)
VALUES (
  'magistrados',
  'Magistrados',
  'Lista de magistrados (desembargadores e juízes) para seleção em decisões judiciais'
)
ON CONFLICT (key) DO NOTHING;

-- Popular com a lista de magistrados
INSERT INTO public.option_items (option_set_id, value, label, "order", is_active)
SELECT 
  (SELECT id FROM public.option_sets WHERE key = 'magistrados'),
  magistrado,
  magistrado,
  row_number,
  true
FROM (
  VALUES
    ('Desembargador Amauri Pinto Ferreira', 1),
    ('Desembargador Alberto Deodato Neto', 2),
    ('Desembargador Alberto Diniz Junior', 3),
    ('Desembargador Alberto Vilas Boas', 4),
    ('Desembargador Alexandre Santiago', 5),
    ('Desembargador Alexandre Victor de Carvalho', 6),
    ('Desembargador Amorim Siqueira', 7),
    ('Desembargador Anacleto Rodrigues', 8),
    ('Desembargador Antônio Bispo', 9),
    ('Desembargador Arnaldo Maciel', 10),
    ('Desembargador Bruno Terra Dias', 11),
    ('Desembargador Carlos Henrique Perpétuo Braga', 12),
    ('Desembargador Carlos Levenhagen', 13),
    ('Desembargador Carlos Roberto de Faria', 14),
    ('Desembargador Cássio Salomé', 15),
    ('Desembargador Cavalcante Motta', 16),
    ('Desembargador Claret de Moraes', 17),
    ('Desembargador Corrêa Camargo', 18),
    ('Desembargador Corrêa Junior', 19),
    ('Desembargador Danton Soares Martins', 20),
    ('Desembargador Dirceu Walace Baroni', 21),
    ('Desembargador Doorgal Borges de Andrada', 22),
    ('Desembargador Edison Feital Leite', 23),
    ('Desembargador Edilson Olímpio Fernandes', 24),
    ('Desembargador Eduardo Brum', 25),
    ('Desembargador Eduardo Machado', 26),
    ('Desembargador Estevão Lucchesi', 27),
    ('Desembargador Evandro Lopes da Costa Teixeira', 28),
    ('Desembargador Fabiano Rubinger de Queiroz', 29),
    ('Desembargador Fábio Torres de Sousa', 30),
    ('Desembargador Fernando Caldeira Brant', 31),
    ('Desembargador Fernando Lins', 32),
    ('Desembargador Fortuna Grion', 33),
    ('Desembargador Francisco Ricardo Sales', 34),
    ('Desembargador Franklin Higino Caldeira Filho', 35),
    ('Desembargador Gilson Soares Lemes', 36),
    ('Desembargador Glauco Fernandes', 37),
    ('Desembargador Guilherme de Azeredo Passos', 38),
    ('Desembargador Habib Felippe Jabour', 39),
    ('Desembargador Henrique Abi-Ackel Torres', 40),
    ('Desembargador Jair Varão', 41),
    ('Desembargador Jaubert Carneiro Jaques', 42),
    ('Desembargador João Cancio', 43),
    ('Desembargador José Américo Martins da Costa', 44),
    ('Desembargador José Arthur Filho', 45),
    ('Desembargador José Augusto Lourenço dos Santos', 46),
    ('Desembargador José de Carvalho Barbosa', 47),
    ('Desembargador José Eustáquio Lucas Pereira', 48),
    ('Desembargador José Luiz de Moura Faleiros', 49),
    ('Desembargador José Marcos Vieira', 50),
    ('Desembargador Júlio César Lorens', 51),
    ('Desembargador Kildare Carvalho', 52),
    ('Desembargador Leite Praça', 53),
    ('Desembargador Leonardo de Faria Beraldo', 54),
    ('Desembargador Luís Carlos Gambogi', 55),
    ('Desembargador Luiz Artur Hilário', 56),
    ('Desembargador Manoel dos Reis Morais', 57),
    ('Desembargador Marcelo Rodrigues', 58),
    ('Desembargador Marcílio Eustáquio Santos', 59),
    ('Desembargador Marco Aurélio Ferenzini', 60),
    ('Desembargador Marcos Flávio Lucas Padula', 61),
    ('Desembargador Marcos Henrique Caldeira Brant', 62),
    ('Desembargador Marcos Lincoln', 63),
    ('Desembargador Matheus Chaves Jardim', 64),
    ('Desembargador Maurício Soares', 65),
    ('Desembargador Márcio Idalmo Santos Miranda', 66),
    ('Desembargador Moreira Diniz', 67),
    ('Desembargador Narciso Alvarenga Monteiro de Castro', 68),
    ('Desembargador Nelson Missias de Morais', 69),
    ('Desembargador Newton Teixeira Carvalho', 70),
    ('Desembargador Octavio Augusto De Nigris Boccalini', 71),
    ('Desembargador Octávio de Almeida Neves', 72),
    ('Desembargador Oliveira Firmo', 73),
    ('Desembargador Paulo Calmon Nogueira da Gama', 74),
    ('Desembargador Pedro Aleixo', 75),
    ('Desembargador Pedro Bernardes de Oliveira', 76),
    ('Desembargador Pedro Bitencourt Marcondes', 77),
    ('Desembargador Peixoto Henriques', 78),
    ('Desembargador Raimundo Messias Júnior', 79),
    ('Desembargador Ramom Tácio', 80),
    ('Desembargador Renato Dresch', 81),
    ('Desembargador Roberto Paiva Júnior', 82),
    ('Desembargador Roberto Vasconcellos', 83),
    ('Desembargador Rogério Medeiros', 84),
    ('Desembargador Rui de Almeida Magalhães', 85),
    ('Desembargador Sálvio Chaves', 86),
    ('Desembargador Sérgio André da Fonseca Xavier', 87),
    ('Desembargador Valladares do Lago', 88),
    ('Desembargador Versiani Penna', 89),
    ('Desembargador Vicente de Oliveira Silva', 90),
    ('Desembargador Wagner Wilson', 91),
    ('Desembargador Wanderley Paiva', 92),
    ('Desembargador Wilson Benevides', 93),
    ('Desembargador Agostinho Gomes de Azevedo', 94),
    ('Desembargadora Alice Birchal', 95),
    ('Desembargadora Âmalin Aziz Sant''Ana', 96),
    ('Desembargadora Ana Paula Caixeta', 97),
    ('Desembargadora Ângela de Lourdes Rodrigues', 98),
    ('Desembargadora Aparecida Grossi', 99),
    ('Desembargadora Áurea Brasil', 100),
    ('Desembargadora Beatriz Pinheiro Caires', 101),
    ('Desembargadora Cláudia Maia', 102),
    ('Desembargadora Evangelina Castilho Duarte', 103),
    ('Desembargadora Jaqueline Calábria Albuquerque', 104),
    ('Desembargadora Juliana Campos Horta', 105),
    ('Desembargadora Kárin Emmerich', 106),
    ('Desembargadora Lílian Maciel', 107),
    ('Desembargadora Luzia Divina de Paula Peixôto', 108),
    ('Desembargadora Maria Cristina Cunha Carvalhais', 109),
    ('Desembargadora Maria das Graças Rocha Santos', 110),
    ('Desembargadora Maria Inês Souza', 111),
    ('Desembargadora Maria Luíza de Marilac', 112),
    ('Desembargadora Mônica Libânio', 113),
    ('Desembargadora Paula Cunha e Silva', 114),
    ('Desembargadora Sandra Fonseca', 115),
    ('Desembargadora Shirley Fenzi Bertão', 116),
    ('Desembargadora Teresa Cristina da Cunha Peixoto', 117),
    ('Desembargadora Valéria Rodrigues', 118),
    ('Desembargadora Yeda Athias', 119),
    ('Não Disponível / Não Cadastrado', 999)
) AS magistrados_data(magistrado, row_number)
ON CONFLICT DO NOTHING;